server:
  port: ${PORT:8080}
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/labdb?createDatabaseIfNotExist=true}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
management:
  endpoints.web.exposure.include: health,info
  endpoint.health.probes.enabled: true

